name: Deploy

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest
    env:
      OAUTH__CLIENTAPPID: ${{ secrets.CLIENT_APP_ID }}
      OAUTH__CLIENTAPPSECRET: ${{ secrets.CLIENT_APP_SECRET }}

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 9.0.x

    - name: Install MAUI Workload
      run: dotnet workload install maui

    - name: Restore
      run: dotnet restore
      working-directory: ./src/TaxDashboard

    - name: Build
      run: dotnet build -c Release -f:net9.0-windows10.0.19041.0
      working-directory: ./src/TaxDashboard

    - name: Decode Signing Certificate
      run: |
        echo "${{ secrets.SIGNING_CERTIFICATE_BASE64_CONTENT }}" > TaxDashboard_Certificate.asc
        certutil -decode TaxDashboard_Certificate.asc TaxDashboard_Certificate.pfx
        
    - name: Installing Signing Certificate
      run: certutil -user -p "${{ secrets.SIGNING_CERTIFICATE_PASSWORD }}" -Silent -importpfx TaxDashboard_Certificate.pfx NoRoot

    - name: Publish
      run: dotnet publish -c Release -f:net9.0-windows10.0.19041.0 /p:GenerateAppxPackageOnBuild=true /p:AppxPackageSigningEnabled=true /p:PackageCertificateThumbprint=${{ secrets.SIGNING_CERTIFICATE_THUMBPRINT }}
      working-directory: ./src/TaxDashboard 
      
    - name: Extract Version
      id: extractVersion
      shell: pwsh
      run: |
        $xml = [Xml] (Get-Content ./src/TaxDashboard/TaxDashboard.csproj)
        [string] $version = [Version] $xml.Project.PropertyGroup.ApplicationDisplayVersion
        echo "version=$($version)" >> $env:GITHUB_OUTPUT

    - name: Create Tag
      uses: actions/github-script@v5
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          github.rest.git.createRef({
            owner: context.repo.owner,
            repo: context.repo.repo,
            sha: context.sha,
            ref: 'refs/tags/v${{ steps.extractVersion.outputs.version }}'
          })
          
    - name: Rename Auto Update Installer
      shell: pwsh
      run: Rename-Item ./src/TaxDashboard/bin/Release/net9.0-windows10.0.19041.0/win10-x64/AppPackages/TaxDashboard_${{ steps.extractVersion.outputs.version }}.0_Test/TaxDashboard_${{ steps.extractVersion.outputs.version }}.0_x64.msix AutoUpdate.msix
            
    - name: Rename Certificate
      shell: pwsh
      run: Rename-Item ./src/TaxDashboard/bin/Release/net9.0-windows10.0.19041.0/win10-x64/AppPackages/TaxDashboard_${{ steps.extractVersion.outputs.version }}.0_Test/TaxDashboard_${{ steps.extractVersion.outputs.version }}.0_x64.cer TaxDashboard.cer

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v${{ steps.extractVersion.outputs.version }}
        files: |
          ./src/TaxDashboard/TaxDashboard.appinstaller
          ./src/TaxDashboard/bin/Release/net9.0-windows10.0.19041.0/win10-x64/AppPackages/TaxDashboard_${{ steps.extractVersion.outputs.version }}.0_Test/AutoUpdate.msix
          ./src/TaxDashboard/bin/Release/net9.0-windows10.0.19041.0/win10-x64/AppPackages/TaxDashboard_${{ steps.extractVersion.outputs.version }}.0_Test/TaxDashboard.cer
